### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by thaysom22**
* server creation for app moved to separate start.js module to allow server class to be imported for integration testing of API
* implements endpoint to upload snome photos to aws s3 as part of createSnome (not tested yet)
* add aws-sdk and multer dependencies
* implemented basic test for get endpoint
* adds script 'database:shell' to execute sql directly against postgres instance in docker container

### CODE REVIEW

**Comment by thaysom22** [comment]
please note the 'database:shell' scipt added to package.json: this can be used to verify endpoints as they are built

**Comment by zbretz** [comment]
Hey @thaysom22 I started to review this. Looks great so far! I'm stepping away for a few hours and plan to complete the review and merge when I'm back. Just thought I'd update.

**Comment by thaysom22** [comment]
hey @zbretz - routes.js appears to be causung conflict. The main chnages I made in there was to organize the routes by model inside the file so it is easier to read (advice from @raphaelspies )

**Comment by zbretz** [comment]
Unfortunately github isn't allowing me to resolve the conflict in-browser. I'm going to follow an alternate procedure they're providing. I'm probably going to 'close' this PR as a result, but we should see all f your commits reflected in the backend branch once it's complete. I'm happy to revisit this if it doesn't go the way I/we would expect.

**Pull request merged**
